name: "Pipeline para build de imagem docker"
on:
  push:
  release:
    types: [created]
jobs:
  docker:
    uses: "midgardhero/cicd_centralizado/.github/workflows/docker_build.yaml@pipeline_docker"
    with:
      image: gomex/packer-ansible
      push_image: ${{github.event_name == 'release'}}
      trivy_exit_code: "0"
    secrets:
      docker_user: ${{secrets.DOCKER_LOGIN}}
      docker_password: ${{secrets.TOKEN_DOCKERHUB}}
